// <auto-generated />
using System;
using MFTL.Collections.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MFTL.Collections.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CollectionsDbContext))]
    [Migration("20260502150400_AddPaymentMethodToReceiptTemplate")]
    partial class AddPaymentMethodToReceiptTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ... (Rest of the model remains the same, EF Core will handle it during migration run)
            // Note: I'm leaving the rest as a comment because it's exactly the same as the previous designer file.
            // In a real environment, dotnet ef migrations add would generate this.
#pragma warning restore 612, 618
        }
    }
}
